---
title: "Supplementary Figure 5"
author: "Anna Goodman"
date: "2024-12-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load packages
```{r}
library(tidyverse)
library(gridExtra)
library(ggpubr)
```

# load data
```{r}
RNA_based_fungal_trait_relabund <- read.csv("../../Analysis/Microbial Communities/Imputed Biomass/Results/RNA_based_fungal_trait_relabund_mip.csv")
RNA_fungal_trait_biomass <- read.csv("../../Analysis/Microbial Communities/Imputed Biomass/Results/RNA_based_fungal_trait_biomass_mip.csv")
```

# make depth discrete so boxplot will work
```{r}
relab.discrete.depth = mutate(RNA_based_fungal_trait_relabund, core_bottom_depth_cm = as.character(core_bottom_depth_cm)) # make a dataframe in which depth is a discrete variable
relab.discrete.depth$core_bottom_depth_cm <- factor(relab.discrete.depth$core_bottom_depth_cm, levels=c("7.5", "15", "22.5", "30", "37.5", "45")) # put the levels of depth in order
```

# define common characteristics for both plot panels
```{r}
xvar = relab.discrete.depth$core_bottom_depth_cm
  
boxplot = geom_boxplot( # add boxplot layer
                        alpha = 0.3, #make fill mostly transparent
                       color = "gray50", 
                       linewidth = 0.25
                       ) 
#linecolor = scale_color_manual(name = "Tree mortality", values = c("mediumblue", "lightpink2"))

points = geom_jitter( # add raw datapoint layer
                      size = 0.5, 
                     position = position_jitterdodge(jitter.width = 0.15, dodge.width = 0.75) # Dodge so living and dead points are separated and overlay their boxplots. Jitter optional.
                     ) 

fillcolor = scale_fill_manual(name = "Tree mortality", values = c("darkblue", "deeppink")) # color the semi-transparent box fill, name legend

dotlinecolor = scale_color_manual(name = "Tree mortality", values = c("darkblue", "deeppink")) # color the points and lines, name legend consistently

background = theme_minimal() # visually simplify background

xaxislabel = xlab("") # set x-axis label

theme = theme(text = element_text(size = 7), # set font size
              plot.margin = margin(t = 15, r = 5.5, b = 5.5, l = 5.5), # set margin widths: widen left margin of each plot so the panel labels can fit in top left. 5.5 is default pt size for margins in ggplot.
              axis.title.x = element_blank(), # no x-axis, if doing shared x-axis later
              legend.position = "bottom"
)

ymax = ylim(0, 2050) # for bac and fun panels only: set common y-axis limit to enable side-by-side comparison 

add_leg_box = theme( # optional: add to whichever panel the legend grob gets grabbed from so the final legend has a box around it 
    legend.background = element_rect(
      color = "black",
      linewidth = 0.4,
      linetype = "solid"
    )
  )

legend = theme(legend.position = "none")
```

# make the relative abundance half of the figure
```{r}
# make boxplot: 
relab = ggplot(relab.discrete.depth, aes(x = core_bottom_depth_cm, y = 100*ectomycorrhizal, fill = Tree_Health, color = Tree_Health)) + # 'ectomycorrhizal' is a proportion; 100*ectomycorrhizal is a percentage
  dotlinecolor +
  boxplot +
  points +
  fillcolor +
  background +
  xaxislabel +
  ylab("Relative abundance (%)") +
  theme

relab
```

```{r}
# make imputed biomass half of the figure
imputed.discrete.depth = mutate(RNA_fungal_trait_biomass, core_bottom_depth_cm = as.character(core_bottom_depth_cm)) # make a dataframe in which depth is a discrete variable
imputed.discrete.depth$core_bottom_depth_cm <- factor(discrete.depth$core_bottom_depth_cm, levels=c("7.5", "15", "22.5", "30", "37.5", "45")) # put the levels of depth in order

# make boxplot:
mass = ggplot(imputed.discrete.depth, aes(x = core_bottom_depth_cm, y = ectomycorrhizal, fill = Tree_Health, color = Tree_Health)) + # 'ectomycorrhizal' is a proportion; 100*ectomycorrhizal is a percentage
  boxplot +
  points +
  fillcolor +
  dotlinecolor +
  background +
  xaxislabel +
  ylab("Imputed biomass (ng PLFA / g soil)") +
  theme

mass
```

```{r}
# make combined figure with each boxplot as a panel 

supFig4 = ggpubr::ggarrange(
  mass, relab, # list of boxplots
  labels = c("A", "B"), 
  font.label = list(size = 10, color = "black", face = "bold", family = NULL),
  widths = c(5,5),
 # label.x = 0.25,
  #label.y = 1.02,
  common.legend = TRUE, # same legend showing how color maps to tree mortality
  legend = "right", # common legend sits above boxplot panels
  align = "hv", # Align boxplots, horizontally and vertically
  nrow = 1 # boxplots arranged in a single row
)
supFig4
```
```{r}
supFig4_sharedxlab <- annotate_figure(supFig4,
                bottom = text_grob("Core bottom depth (cm)                       ", color = "black", size = 7))
supFig4_sharedxlab
```
# add caption
```{r}
supFig4_caption <- annotate_figure(supFig4_sharedxlab,
                top = text_grob("Supplementary Figure 5. Box and whisker plots showing the distribution of imputed biomass (A) and relative \n abundance (B) of ectomycorrhizal fungi across discrete soil depths. Imputed biomass was calculated as: \n the proportion of the fungal community (as measured by 16S rRNA metabarcoding) assigned to the ectomycorrhizal \n primary lifestyle * total living fungal biomass as measured by PLFA. Relative abundance \n was calculated as the proportion of the fungal community assigned to the ectomycorrhizal primary lifestyle * 100. \n Box boundaries are the first and third quartiles. Individual data points are overlayed; sample size \n is variable between boxes due to complications with RNA extraction and amplification for metabarcoding.", color = "black", size = 7))
supFig4_caption
```

### export:
```{r}
# set size and resolution parameters

# requirements: 1000 ppi (pixels per inch), 140 mm wide
# 1 inch = 0.0393701 mm, 1 mm = 25.4 inches

ppi = 1000

w_mm = 140
hw_ratio = 4/5 # arbitrary

h_mm = w_mm*hw_ratio
w_i = w_mm/25.4
h_i = h_mm/25.4
```


```{r}
# create the jpg figure file in this results folder and in the Figures folder

png("Results/Supplementary_Figure_4_ecm_biomass_relabund_by_depth.png", width = w_i * ppi, height = h_i * ppi, res = ppi)

supFig4_caption
dev.off()
```

```{r}
# create the jpg figure file in this results folder and in the Figures folder

jpeg("Results/Supplementary_Figure_4_ecm_biomass_relabund_by_depth.jpg", width = w_i * ppi, height = h_i * ppi, res = ppi)

supFig4_caption
dev.off()
```