---
title: "Supplementary_Figure_6"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#load required packages:
```{r}
library("phyloseq")
library("tidyverse")
```

#load required data:
```{r}
ps16S_positive = read_rds("../../Analysis/Microbial Communities/Fungal-Bacterial Interactions/DeSeq2 Indicator Species Analysis/Results/ps16S_ASVs_RNA_positive_mip.rds")
```

# 
```{r}

# Melt relativized phyloseq object of positively-influenced 16S ASVs into a long dataframe
df <- psmelt(ps16S_positive)

df <- df %>%
  mutate(
    Tree_label = paste0(Tree, ", ", core_bottom_depth_cm, " cm")
  )

# Get unique combinations of sample data and sort
sample_order <- df %>%
  select(Sample, Tree_Health, Tree, core_bottom_depth_cm) %>%
  distinct() %>%
  arrange(Tree_Health, Tree, core_bottom_depth_cm) %>%
  pull(Sample)

# Relevel the Sample factor to reflect this order
df$Sample <- factor(df$Sample, levels = sample_order)

# Create label vector with names matching Sample IDs
sample_labels <- df %>%
  distinct(Sample, Tree_label) %>%
  deframe()  # converts two-column data frame to named vector


```


```{r}
text_size = 7
supfig5 = ggplot(df, aes(x = Sample, y = Abundance, fill = Phylum)) +
  geom_bar(stat = "identity", position = "stack") +
  facet_wrap(~ Tree_Health, scales = "free_x") +
  scale_x_discrete(labels = sample_labels) +
  scale_fill_discrete(labels = function(x) gsub("p__", "", x)) +
  theme_minimal(base_size = text_size) +
  theme(
    axis.text = element_text(size = text_size),
    axis.title = element_text(size = text_size),
    legend.text = element_text(size = text_size),
    legend.title = element_text(size = text_size),
    strip.text = element_text(size = text_size),
    plot.title = element_text(size = text_size),
    plot.subtitle = element_text(size = text_size),
    plot.caption = element_text(size = text_size),
    axis.text.x = element_text(angle = 90, hjust = 1),
    legend.key.size = unit(0.2, "cm")
  ) +
  ylab("Relative abundance") +
  xlab("Soil core") +
  labs(fill = "Phylum")

```

# add caption
```{r}
supFig4_caption <- annotate_figure(supFig4_sharedxlab,
                top = text_grob("Supplementary Figure 5. Box and whisker plots showing the distribution of imputed biomass (A) and relative \n abundance (B) of ectomycorrhizal fungi across discrete soil depths. Imputed biomass was calculated as: \n the proportion of the fungal community (as measured by 16S rRNA metabarcoding) assigned to the ectomycorrhizal \n primary lifestyle * total living fungal biomass as measured by PLFA. Relative abundance \n was calculated as the proportion of the fungal community assigned to the ectomycorrhizal primary lifestyle * 100. \n Box boundaries are the first and third quartiles. Individual data points are overlayed; sample size \n is variable between boxes due to complications with RNA extraction and amplification for metabarcoding.", color = "black", size = 7))
supFig4_caption
```

### export:
```{r}
# create the figure file in this results folder

# requirements: 1000 pp1 (pixels per inch), 140 mm wide
# 1 inch = 0.0393701 mm, 1 mm = 25.4 inches

ppi = 300

w_mm = 140
hw_ratio = 5/11 # arbitrary

h_mm = w_mm*hw_ratio
w_i = w_mm/25.4
h_i = h_mm/25.4

jpeg("Results/sup_fig_6_ecm_promoted_bac_relabund.jpg", width = w_i * ppi, height = h_i * ppi, res = ppi)


supfig5
dev.off()
```






