---
title: "tree ID exploration"
author: "Anna Goodman"
date: "2024-11-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(ggpubr)
```

```{r}
# nucleic acid-based relative abundance data load-in

#   relative abundance data:
Primary_lifestyle_by_sample <- read.csv("../../Analysis/Microbial Communities/Assign_traits_ITS/Results/ITS_Functions_By_Sample/Primary_lifestyle_by_sample_mip.csv")

#  ^ that file only identifies samples by their primer pairs and doesn't have the metadata we need (tree health, depth, tree ID). loading in phyloseq metadata for tree health and depth

#   phyloseq metadata:
phyloseq_metadata_ITS <- read.csv("../../TidyData/Metadata/Results/phyloseq_metadata_ITS_mip.csv")


# add DO_ID, tree health, depth, and nucleic acid to Primary lifestyle by sample
#   just taking the info we need from phyloseq_metadata_ITS
phyloseq_metadata_ITS = select(phyloseq_metadata_ITS, c(phyloseq_name, DO_ID, core_bottom_depth_cm, Tree_Health, nucleic_acid))
#   renaming the column which contains the primer pair ID in Primary_lifestyle_by_sample to match the same in phyloseq_metadata_ITS ("phyloseq_name")
Primary_lifestyle_by_sample = rename(Primary_lifestyle_by_sample, phyloseq_name = Primary_lifestyle)

#   join by phyloseq_name
lifestyle_with_IDs = full_join(phyloseq_metadata_ITS, Primary_lifestyle_by_sample, by = "phyloseq_name")

#REMOVE DNA
lifestyle_with_IDs = filter(lifestyle_with_IDs, nucleic_acid == "RNA")

# remove controls
lifestyle_with_IDs = filter(lifestyle_with_IDs, (is.na(core_bottom_depth_cm) == FALSE))

# break up the DO_ID so we have access to Tree as a variable
lifestyle_with_IDs <- lifestyle_with_IDs %>%
  separate(DO_ID, into = c("DO", "Tree", "depth"), sep = "_")
```

# Make supplementary figure 7
```{r}
supFig7 = ggplot(lifestyle_with_IDs, aes(x = Tree, y = 100*ectomycorrhizal, fill = Tree_Health)) +
  geom_boxplot() +
  labs(x = "Tree ID", y = "Relative abundance of ectomycorrhizal fungi (%)") +
  theme_minimal() + scale_fill_discrete(name = "Tree mortality")
supFig7
```
# load data
```{r}
RNA_based_fungal_trait_relabund <- read.csv("../../Analysis/Microbial Communities/Imputed Biomass/Results/RNA_based_fungal_trait_relabund_mip.csv")
```

# group trees by mortality
```{r}
relab = RNA_based_fungal_trait_relabund
relab$Tree <- factor(relab$Tree, levels=c("T02", "T05", "T07", "T03", "T04", "T06")) # order trees so all three dead trees go first, then all three living trees
```

# use same plot characteristics as fig 1 and supfig 4
```{r}
xvar = relab$core_bottom_depth_cm
  
boxplot = geom_boxplot( # add boxplot layer
                        alpha = 0.3, #make fill mostly transparent
                       color = "gray50", 
                       linewidth = 0.25
                       ) 
#linecolor = scale_color_manual(name = "Tree mortality", values = c("mediumblue", "lightpink2"))

points = geom_jitter( # add raw datapoint layer
                      size = 0.5, 
                     position = position_jitterdodge(jitter.width = 0.15, dodge.width = 0.75) # Dodge so living and dead points are separated and overlay their boxplots. Jitter optional.
                     ) 

fillcolor = scale_fill_manual(name = "Tree mortality", values = c("darkblue", "deeppink")) # color the semi-transparent box fill, name legend

dotlinecolor = scale_color_manual(name = "Tree mortality", values = c("darkblue", "deeppink")) # color the points and lines, name legend consistently

background = theme_minimal() # visually simplify background

xaxislabel = xlab("") # set x-axis label

theme = theme(text = element_text(size = 7), # set font size
              plot.margin = margin(t = 15, r = 5.5, b = 5.5, l = 5.5), # set margin widths: widen left margin of each plot so the panel labels can fit in top left. 5.5 is default pt size for margins in ggplot.
              axis.title.x = element_blank(), # no x-axis, if doing shared x-axis later
              legend.position = "right"
)

ymax = ylim(0, 2050) # for bac and fun panels only: set common y-axis limit to enable side-by-side comparison 

```

# Make supplementary figure 6
```{r}
# make boxplot: 
supFig6 = ggplot(relab, aes(x = Tree, y = 100*ectomycorrhizal, fill = Tree_Health, color = Tree_Health)) + # 'ectomycorrhizal' is a proportion; 100*ectomycorrhizal is a percentage
  dotlinecolor +
  boxplot +
  points +
  fillcolor +
  background +
  xaxislabel +
  ylab("Relative abundance (%)") +
  theme

supFig6
```

```{r}
supFig6_caption <- annotate_figure(supFig6,
                bottom = text_grob("Supplementary Figure 6. Box and whisker plot showing the relative abundance of ectomycorrhizal fungi \n underneath each tree, including data from all soil depths for which fungal community (as measured by 16S \n rRNA metabarcoding) data was availible. Relative abundance was calculated as proportion of the fungal \n community assigned to the ectomycorrhizal primary lifestyle * 100. Box boundaries are the first and \n third quartiles. Sample size is variable between boxes due to complications with RNA extraction and \n amplification for metabarcoding; from left to right, n = 4, 5, 3, 4, 4, 3.", color = "black", size = 7))
supFig6_caption
```

### export:
```{r}
# create the figure file in this results folder


ppi = 300

w_mm = 140
hw_ratio = 8/11 # arbitrary

h_mm = w_mm*hw_ratio
w_i = w_mm/25.4
h_i = h_mm/25.4

```

```{r}
jpeg("Results/sup_fig_6_ecm_relabund_by_tree.jpg", width = w_i * ppi, height = h_i * ppi, res = ppi)


supFig6_caption
dev.off()
```

```{r}
png("Results/sup_fig_6_ecm_relabund_by_tree.png", width = w_i * ppi, height = h_i * ppi, res = ppi)


supFig6_caption
dev.off()
```
# generate tree-specific averages of ecm relative abundance in live trees

```{r}
t3 = filter(lifestyle_with_IDs, lifestyle_with_IDs$Tree == "T03")
t4 = filter(lifestyle_with_IDs, lifestyle_with_IDs$Tree == "T04")
t6 = filter(lifestyle_with_IDs, lifestyle_with_IDs$Tree == "T06")

t3 = filter(t3, !(is.na(t3$ectomycorrhizal)))
t4 = filter(t4, !(is.na(t4$ectomycorrhizal)))


t3avg = mean(t3$ectomycorrhizal)
t4avg = mean(t4$ectomycorrhizal)
t6avg = mean(t6$ectomycorrhizal)

t3avg
t4avg
t6avg
```


------------------------------------------------------------------------------

```{r}
# make another version of supplementary figure 7 with additional features: paneling by tree health, shaped points representing different depths 
#I didn't end up using this 

discrete.depth = mutate(lifestyle_with_IDs, core_bottom_depth_cm = as.character(core_bottom_depth_cm))
discrete.depth$core_bottom_depth_cm <- factor(discrete.depth$core_bottom_depth_cm, levels=c("7.5", "15", "22.5", "30", "37.5", "45"))

# broken at the moment
supFig7 = ggplot(discrete.depth, aes(x = Tree, y = 100*ectomycorrhizal, fill = Tree_Health)) +
  geom_boxplot() +
  facet_wrap(~Tree_Health) + 
  labs(x = "tree ID", y = "% EcMF of soil fungal community") + 
  geom_point(data = discrete.depth, aes(x = Tree, y = 100*ectomycorrhizal, shape = core_bottom_depth_cm), show.legend = TRUE) +
  geom_jitter(width = 0.2, height = 0.2) +
  theme_minimal()

supFig7
```

```{r}
# another version of sup fig 7 that just has the data from below 20cm
just_deep = filter(lifestyle_with_IDs, lifestyle_with_IDs$core_bottom_depth >20 )
ggplot(just_deep, aes(x = Tree, y = 100*ectomycorrhizal, fill = Tree_Health)) +
  geom_boxplot() + geom_point() +
  facet_wrap(~Tree_Health) + # Group the boxes by treatment B
  labs(x = "tree ID", y = "% EcMF of soil fungal community") +
  theme_minimal()
```




# visualize ecm-associated biomass by tree
```{r}
# just the biomass of ecm assoicated bacteria
metadata_with_ECMasssociated <- read.csv("../../Analysis/Microbial Communities/Fungal-Bacterial Interactions/DeSeq2 Indicator Species Analysis/Results/metadata_with_ECMasssociated3trees_mip.csv")
ggplot(metadata_with_ECMasssociated, aes(x = Tree, y = ECM_associated_16S_ng_g, fill = Tree_Health)) +
  geom_boxplot() +
  facet_wrap(~Tree_Health) + # Group the boxes by treatment B
  labs(x = "Tree ID", y = "mass of bacteria which were ecm associated ng/gsoil") +
  theme_minimal()
```
```{r}
# biomass of ecm assoicated bacteria and ecm together

ggplot(metadata_with_ECMasssociated, aes(x = Tree, y = ECM_associated_biomass, fill = Tree_Health)) +
  geom_boxplot() +
  facet_wrap(~Tree_Health) + # Group the boxes by tree health
  labs(x = "tree", y = "ecm biomass + ecm-associated bacterial biomass ng/g soil") +
  theme_minimal()

t3 = filter(metadata_with_ECMasssociated, metadata_with_ECMasssociated$Tree == "T03")
t4 = filter(metadata_with_ECMasssociated, metadata_with_ECMasssociated$Tree == "T04")
t6 = filter(metadata_with_ECMasssociated, metadata_with_ECMasssociated$Tree == "T06")

t3 = filter(t3, !(is.na(t3$ectomycorrhizal)))
t4 = filter(t4, !(is.na(t4$ectomycorrhizal)))


t3avg = mean(t3$ectomycorrhizal)
t4avg = mean(t4$ectomycorrhizal)
t6avg = mean(t6$ectomycorrhizal)
```
# visualize C:N ratio by tree
```{r}

ggplot(metadata_with_ECMasssociated, aes(x = Tree, y = C_per_N_Ratio, fill = Tree_Health)) +
  geom_boxplot() +
  facet_wrap(~Tree_Health) + # Group the boxes by treatment B
  labs(x = "tree", y = "C:N") +
  theme_minimal()
```