---
title: "Co-occurence"
author: "Anna Goodman"
date: "2026-03-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(phyloseq)
library(tidyverse)
```

Load in phyloseq objects
```{r}
fun_rna = readRDS("../../TidyData/Phyloseq/Tidy_relativize_phyloseq_objects/Results/psITS_relative_RNA_mip.rds")
bac_rna = readRDS("../../TidyData/Phyloseq/Tidy_relativize_phyloseq_objects/Results/ps16S_relative_RNA_mip.rds")
```

collapse fungi to genus
```{r}
# first see what it looked like before
fun_tt = data.frame(tax_table(fun_rna))
colnames(fun_tt)
```

```{r}
# save a reference key mapping lifestyles to genera
lifestyle_ref <- fun_tt %>%
  group_by(Genus) %>% # Or use your Smart_Name logic here
  summarise(Primary_lifestyle = paste(unique(na.omit(Primary_lifestyle)), collapse = ", "))
```

```{r}
# Agglomerate fungi by Genus
ps_fun_gen <- tax_glom(fun_rna, taxrank = "Genus", NArm = FALSE)
```

```{r}
# tidy fungal agglomeration

# extract the taxa table as a data frame to make it easier to manipulate
tax_df <- as.data.frame(tax_table(ps_fun_gen))

# create a 'unique name' column in tax_df, containing the genus OR most specific named rank
tax_df$Unique_Node_Name <- apply(tax_df, 1, function(x) { # perform the following function row by row (ASV by ASV)
  # store a version of each row which doesn't contain columns with NAs and empty strings as a vector
  clean_row <- x[!is.na(x) & x != ""]
  
  # store the the most specific taxonomic rank in this row/for this ASV. should be the last one in this vector
  most_specific <- tail(clean_row, 1)
  
  # looking at the original row again: if Genus is missing, or if two families have the same genus name, paste "Unclass_" to the stored class name above
  if (is.na(x["Genus"]) | x["Genus"] == "") {
    return(paste0("Unclass_", most_specific))
  } else {
    return(as.character(x["Genus"]))
  } # returned values get stored as tax_df$Unique_Name[this row]
})

# just in case of matching genus names that are actually distinct taxa, make the Unique_Node_Name "genus_family"
tax_df <- tax_df %>%
  group_by(Genus) %>% # group by genus
  mutate(Unique_Node_Name = ifelse(!is.na(Genus) & n_distinct(Family) > 1, 
                             paste0(Genus, "_", Family), 
                             Unique_Node_Name)) %>%
  ungroup()

# overwrite genus column in tax_df with the unique node names
tax_df$Genus = tax_df$Unique_Node_Name
```

```{r}
# agglomerate again, so asvs with unclassified genera are grouped by their highest classification
ps_fun_nodes <- tax_glom(ps_fun_gen, taxrank = "Genus", NArm = FALSE) 
```

```{r}
# rebuild the phyloseq object

# first, put primary lifestyles back on
tax_df_pl = tax_df %>% 
  left_join(lifestyle_ref, by = "Genus") %>%
  rename(Primary_lifestyle = Primary_lifestyle.y) %>%
  select(c(Kingdom, Phylum, Class, Order, Family, Genus, Primary_lifestyle, -Primary_lifestyle.x))

# Replace long ASV strings with these Unique_Node_Names in both tables of the ps object
tax_df_pl = as.data.frame(tax_df_pl) #coerce back to data.frame from tibble
taxa_names(ps_fun_nodes) <- tax_df_pl$Genus # taxa_names(ps_object) goes straight to the columns of the otu table
rownames(tax_df_pl) <- tax_df_pl$Genus # fixes row names of the tax table, but as a data frame

# Put the modified taxa table back into the ps object
tax_table(ps_fun_nodes) <- as.matrix(tax_df_pl)
```

```{r}
# quick check
head(rownames(tax_table(ps_fun_nodes))) # should be unique node names
```


collapse bacteria to genus
```{r}
# Agglomerate fungi by Genus
ps_bac_gen <- tax_glom(bac_rna, taxrank = "Genus", NArm = FALSE)
```

```{r}
# tidy bacterial agglomeration

# extract the taxa table as a data frame to make it easier to manipulate
tax_df <- as.data.frame(tax_table(ps_bac_gen))

# create a 'unique name' column in tax_df, containing the genus OR most specific named rank
tax_df$Unique_Node_Name <- apply(tax_df, 1, function(x) { # perform the following function row by row (ASV by ASV)
  # store a version of each row which doesn't contain columns with NAs and empty strings as a vector
  clean_row <- x[!is.na(x) & x != "" & x != "g__" & x != "f__" & x != "o__" & x != "c__"& x != "p__" & x != "k__"]
  
  # store the the most specific taxonomic rank in this row/for this ASV. should be the last one in this vector
  most_specific <- tail(clean_row, 1)
  
  # looking at the original row again: if Genus is missing, or if two families have the same genus name, paste "Unclass_" to the stored class name above
  if (is.na(x["Genus"]) | x["Genus"] == "g__") {
    return(paste0("Unclass_", most_specific))
  } else {
    return(as.character(x["Genus"]))
  } # returned values get stored as tax_df$Unique_Name[this row]
})

# just in case of matching genus names that are actually distinct taxa, make the Unique_Node_Name "genus_family"
tax_df <- tax_df %>%
  group_by(Genus) %>% # group by genus
  mutate(Unique_Node_Name = ifelse(!(Genus == "g__") & n_distinct(Family) > 1, 
                             paste0(Genus, "_", Family), 
                             Unique_Node_Name)) %>%
  ungroup()

# overwrite genus column in tax_df with the unique node names
tax_df$Genus = tax_df$Unique_Node_Name
```

```{r}
# agglomerate again, so asvs with unclassified genera are grouped by their highest classification
ps_bac_nodes <- tax_glom(ps_bac_gen, taxrank = "Genus", NArm = FALSE) 
```


```{r}
# Replace long ASV strings with these Unique_Node_Names in both tables of the ps object
tax_df = as.data.frame(tax_df) #coerce back to data.frame from tibble
taxa_names(ps_bac_nodes) <- tax_df$Unique_Node_Name # taxa_names(ps_object) goes straight to the columns of the otu table
rownames(tax_df) <- tax_df$Unique_Node_Name # fixes row names of the tax table, but as a data frame

# Put the modified taxa table back into the ps object
tax_table(ps_bac_nodes) <- as.matrix(tax_df)
```

```{r}
# quick check
head(rownames(tax_table(ps_bac_nodes))) # should be unique node names
```


make sample names (columns in otu table) describe soil cores, not barcode pairs

```{r}
# get our otu tables out here
bac_otu = as.data.frame(otu_table(ps_bac_nodes))
fun_otu = as.data.frame(otu_table(ps_fun_nodes))
```


```{r}
eam = read_csv("../../TidyData/Metadata/Results/extraction_and_amplification_metadata_mip.csv") #read in extraction and amplification metadata, which links barcode pairs to soil core samples

all_barcodes = eam %>%
  select(c(FWD_barcode, REV_barcode, nucleic_acid, amplification, DO_ID)) # trim eam down to relevant info

all_barcodes_DO_R1 = all_barcodes %>% 
  mutate(barcodes = str_c("DO_", REV_barcode, "_", FWD_barcode, "_R1.fastq.gz"))
head(all_barcodes_DO_R1)

better_barcode_key =  all_barcodes_DO_R1 %>% 
  select(barcodes, DO_ID)
```

```{r}
bac_otu_doid <- bac_otu %>% 
  rownames_to_column(var = "barcodes") %>%
  left_join(better_barcode_key, by = "barcodes") %>%
  relocate(DO_ID, .after = barcodes) # moves the ID column to the front instead of being after all the asv-specific columns

bac_otu_doid$DO_ID # worked!
```

```{r}

fun_otu_doid <- fun_otu %>% 
  rownames_to_column(var = "barcodes") %>%
  left_join(better_barcode_key, by = "barcodes") %>%
  relocate(DO_ID, .after = barcodes) # moves the ID column to the front instead of being after all the asv-specific columns

head(fun_otu_doid)
fun_otu_doid$DO_ID # worked!
```

```{r}
write.csv(bac_otu_doid, "Results/bac_otu_genus_glom.csv")
write.csv(fun_otu_doid, "Results/fun_otu_genus_glom.csv")
```





