---
title: "Untitled"
output: html_document
date: "2024-09-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### calculate soil moisture gravimetric percent from soil moisture measurements

#load required packages:
```{r}
library(tidyverse)
```
#load tidy data:
```{r}
soilmoisture <- read_csv("../../TidyData/Soil Moisture/Results/Soil_moisture_Tidy_mip.csv")
```
#calculate soil moisture, remove data intermediates:
```{r}
soilmoisture_calc <- mutate(soilmoisture, FM_minus_tin = FM_soil_plus_tin_mass_g - empty_tin_mass_g)
soilmoisture_calc <- mutate(soilmoisture_calc, AD_minus_tin = AD_soil_plus_tin_mass_g - empty_tin_mass_g)
soilmoisture_calc <- mutate(soilmoisture_calc, OD_minus_tin = OD_soil_plus_tin_mass_g - empty_tin_mass_g)
soilmoisture_calc <- mutate(soilmoisture_calc, PerCMoisture = (FM_minus_tin - OD_minus_tin)/OD_minus_tin * 100)

```
#calculate 
```{r}
soilmoisture_calc <- mutate(soilmoisture_calc, FM_AD_correction = AD_minus_tin/FM_minus_tin)
soilmoisture_calc <- mutate(soilmoisture_calc, FM_OD_correction = OD_minus_tin/FM_minus_tin)
soilmoisture_calc <- mutate(soilmoisture_calc, AD_OD_correction = OD_minus_tin/AD_minus_tin)
```
```{r}
soilmoisture_calc <- select(soilmoisture_calc,
                            Sample_ID,
                            PerCMoisture, FM_AD_correction, FM_OD_correction, AD_OD_correction) 
```

#write calculated soil moisture data:
```{r}
write_csv(soilmoisture_calc, "Results/soilmoisture_calc_mip.csv")
```

