---
title: "Imputing biomass of fungi by primary lifestyle"
author: "Anna Goodman"
date: "2024-12-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load packages
```{r}
library(dplyr)
library(tidyr)
```

# load data
```{r}
Primary_lifestyle_by_sample <- read.csv("../../Microbial Communities/Assign_traits_ITS/Results/ITS_Functions_By_Sample/Primary_lifestyle_by_sample_mip.csv") # file containing relative abundance of fungal "primary lifestyles" within each sample, generated by assigning primary lifestyles to ASVs from both the DNA and rRNA ITS metabarcoding pipelines.

# This file lacks key metadata; rows are only identified by the unique pair of barcoding primers used for each single-nucleic acid subsample during ITS library prep

phyloseq_metadata_ITS <- read.csv("../../../TidyData/Metadata/Results/phyloseq_metadata_ITS_mip.csv") # file containing metadata and barcoding primers from ITS library prep

```

# join trait-based relative abundance data with key metadata
```{r}
Primary_lifestyle_by_sample = rename(Primary_lifestyle_by_sample, phyloseq_name = Primary_lifestyle) # match the names of columns containing the identifying barcoding primer pair (now "phyloseq_name" in both)

relative_abundance = full_join(phyloseq_metadata_ITS, Primary_lifestyle_by_sample, by = "phyloseq_name") # join by phyloseq_name

relative_abundance = filter(relative_abundance, nucleic_acid == "RNA") # remove all DNA-based data; use only rRNA-based data moving forward

relative_abundance = filter(relative_abundance, (is.na(core_bottom_depth_cm) == FALSE)) # remove data from library preparation controls
```

# impute biomass

```{r}
# make a list of all primary lifestyles which appear in the dataset
allLifestyles = c("algal_parasite", 
  "animal_parasite", 
  "arbuscular_mycorrhizal", 
  "dung_saprotroph", 
  "ectomycorrhizal", 
  "epiphyte", 
  "foliar_endophyte",
  "lichen_parasite",
  "lichenized",
  "litter_saprotroph",
  "moss_symbiont",
  "mycoparasite",
  "nectar.tap_saprotroph",
  "plant_pathogen",
  "pollen_saprotroph",
  "protistan_parasite",
  "root_endophyte",
  "soil_saprotroph",
  "sooty_mold",
  "unspecified",
  "unspecified_saprotroph",
  "wood_saprotroph",
  "NA.") 
```

```{r}
imputed_biomass <- relative_abundance # duplicate the dataframe containing relative abundance data
for (var in allLifestyles) { # iterate by column through each primary lifestyle
  for (x in (1:length(imputed_biomass$DO_ID))) { # iterate by row
      massVal = imputed_biomass[x, var] * imputed_biomass[x, "PLFA_Total_Fungi_ng_g"] # impute biomass of a group of fungi as: relative abundance among fungi in the sample * lipid mass of all fungi in the sample
      imputed_biomass[x, var] = massVal # replace the relative abundance value with the biomass value
    }
   }

```

# save both as .csv
```{r}
write.csv(relative_abundance, file = "Results/RNA_based_fungal_trait_relabund_mip.csv") 
write.csv(imputed_biomass, file = "Results/RNA_based_fungal_trait_biomass_mip.csv")
```


